__title__ = 'lottus'
__description__ = 'An ussd library that will save you time'
__version__ = '0.0.2'
__author__ = 'Benjamim Chambule'
__author_email__ = 'benchambule@gmail.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2021 Benjamim Chambule'